#!/usr/bin/env bash
# Enable SSH commit signing only when the signing key is present, then (best
# effort) verify that key is registered as a signing key on GitHub.
#
# Signing config lives in a machine-local include ($SIGNING_INCLUDE) that the
# base .gitconfig pulls in via [include]:
#   key present => write the include  (commits sign)
#   key absent  => remove the include (commits succeed UNSIGNED, never fail)
#
# The GitHub check is read-only: never uploads, never refreshes scopes, never
# prompts. Skips quietly when gh is missing, unauthenticated, or lacks the
# read:ssh_signing_key scope. Non-zero exit only on a hard GitHub API error.
set -euo pipefail

KEY_FILE="${SIGNING_KEY_FILE:-$HOME/.ssh/id_ed25519.pub}"
SIGNING_INCLUDE="${SIGNING_INCLUDE:-$HOME/.config/git/signing.local}"

# --- Local signing toggle (load-bearing: gates whether commits can succeed) ---

if [ ! -r "$KEY_FILE" ]; then
  if [ -e "$SIGNING_INCLUDE" ]; then
    rm -f "$SIGNING_INCLUDE"
    echo "==> git signing: $KEY_FILE absent, disabled signing (commits unsigned)"
  else
    echo "==> git signing: $KEY_FILE absent, signing stays off (commits unsigned)"
  fi
  exit 0
fi

mkdir -p "$(dirname "$SIGNING_INCLUDE")"

# SSH commit signing needs git >= 2.34 (gpg.format=ssh). Older git treats that
# value as a fatal config error, which would break *every* git command once the
# include is loaded. Skip signing entirely on old git rather than wedge the repo.
git_ver="$(git --version | awk '{print $3}')"
ver_ge() { [ "$(printf '%s\n%s\n' "$2" "$1" | sort -V | head -n1)" = "$2" ]; }
if ! ver_ge "$git_ver" "2.34.0"; then
  if [ -e "$SIGNING_INCLUDE" ]; then
    rm -f "$SIGNING_INCLUDE"
  fi
  echo "==> git signing: git $git_ver < 2.34 lacks SSH signing, signing stays off (commits unsigned)"
  exit 0
fi

ALLOWED_SIGNERS="${ALLOWED_SIGNERS:-$HOME/.gitallowedsigners}"
cat > "$SIGNING_INCLUDE" <<EOF
# Generated by setup-git-signing.sh — do not edit. Removed when the signing
# key is absent or git is too old for SSH signing. Pulled in by ~/.gitconfig's
# [include].
[gpg]
	format = ssh
[gpg "ssh"]
	allowedSignersFile = $ALLOWED_SIGNERS
[user]
	signingkey = $KEY_FILE
[commit]
	gpgsign = true
[tag]
	gpgsign = true
EOF
echo "==> git signing: enabled, signing with $KEY_FILE"

# --- GitHub registration check (best effort; never blocks signing) -----------

if ! command -v gh >/dev/null 2>&1; then
  echo "   gh not installed, skipping GitHub key check"
  exit 0
fi

if ! gh auth status >/dev/null 2>&1; then
  echo "   gh not authenticated, skipping GitHub key check (run: gh auth login)"
  exit 0
fi

echo "   checking GitHub for $KEY_FILE"

# Match on the base64 body (field 2 of an OpenSSH pubkey line). Title and the
# trailing comment drift across machines; the body is the identity.
local_body="$(awk '{print $2}' "$KEY_FILE")"
if [ -z "$local_body" ]; then
  echo "   $KEY_FILE has no key body, skipping GitHub check" >&2
  exit 0
fi

# /user/ssh_signing_keys requires read:ssh_signing_key (read) or
# admin:ssh_signing_key (read+write). gh's default login does not include either.
if ! remote_bodies="$(gh api -H 'Accept: application/vnd.github+json' /user/ssh_signing_keys \
  --jq '.[].key' 2>&1)"; then
  if printf '%s\n' "$remote_bodies" | grep -qiE 'scope|admin:ssh_signing_key|read:ssh_signing_key'; then
    echo "   gh token lacks read:ssh_signing_key scope; cannot verify GitHub-side registration" >&2
    echo "   to enable read-only check: gh auth refresh -h github.com -s read:ssh_signing_key" >&2
    exit 0
  fi
  echo "   gh api /user/ssh_signing_keys failed:" >&2
  printf '%s\n' "$remote_bodies" | sed 's/^/   /' >&2
  exit 1
fi

if printf '%s\n' "$remote_bodies" | awk '{print $2}' | grep -qxF "$local_body"; then
  echo "   ok: $KEY_FILE is registered as a GitHub signing key"
  exit 0
fi

echo "   warning: $KEY_FILE is NOT registered as a GitHub signing key" >&2
echo "   commits will sign locally but show 'Unverified' on github.com" >&2
echo "   to fix: upload the public key at https://github.com/settings/ssh/new (key type: Signing Key)" >&2
exit 0
